name: jal_shakti_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fl_chart: ^0.68.0
  google_maps_flutter: ^2.6.1
  csv: ^6.0.0
  url_launcher: ^6.3.2
  geolocator: ^14.0.2
  image_picker: ^1.1.2
  shared_preferences: ^2.2.3 
  intl: ^0.20.2
  
  http: ^1.2.1

  # Dependencies for State Management and Location Services
  flutter_riverpod: ^2.5.1
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

